config/routes.rb
MapsBe::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: {format: :json} do

    devise_for :users,   module: "api"
    devise_for :living_museum_users,   module: "api",  :controllers => {  :sessions=>"api/living_museum_sessions"}
    resource :museums do
      collection do
        get 'getMuseumData'
        post 'setMuseumData'

        post 'createUser'
        post 'destroyUser'
        post 'updateUser'
        get 'getUsers'
        get 'getProfile'

        get 'getCatalogs'
        post 'createCatalog'

        get 'getSections'
        get 'getSectionDetail'
        post 'createSection'
        post 'deleteSection'

        post 'addFieldToSection'
        post 'removeFieldFromSection'
        post 'setFieldDetails'
        post 'updateSection'

        get 'getCard'
        post 'findCard'
        post 'saveCard'
        post 'deleteCard'
        post 'saveImage'
        post 'deleteImage'

        post 'import'
      end

    end
    resource :config
    resources :options

    match "config/getSections", via: [:get, :post]
    match "config/getSectionFieldDetail", via: [:get, :post]
    match "living_museum/reset", via: [:post]
    match "living_museum/createUser", via: [:post]
    match "living_museum/requestResetPassword", via: [:post]
    match "living_museum/resetPassword", via: [:post]

    match "living_museum/searchCards", via: [:get]
    match "living_museum/saveSearch", via: [:post]
    match "living_museum/getSearch", via: [:get]
    match "living_museum/listSearch", via: [:get]
    match "living_museum/deleteSearch", via: [:post]
    match "living_museum/exportCards", via: [:get, :post]
    match "living_museum/downloadLidoXml", via: [:get, :post]
    match "living_museum/getCard", via: :get

  end

   root 'api/base#index'

end

app/models/option.rb
# == Schema Information
#
# Table name: options
#
#  id         :integer          not null, primary key
#  museum_id  :integer
#  name       :string(255)
#  key        :string(255)
#  value      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Option < ActiveRecord::Base

  scope :museum_options ,  ->(museum_id) {where(museum_id: [nil,museum_id])}
  scope :generic_options ,  ->() {where(museum_id: [nil])}
end

app/controllers/api/options_controller.rb
# encoding: UTF-8
class API::OptionsController < ApplicationController
  before_filter :authenticate_user_from_token!
  before_filter :authenticate_museum
  before_filter :allow_cross_domain_access

  def index
    begin
      filter=params.require(:filter)
      if @museum
        @options=Option.museum_options(@museum.id).search(filter).result()
      else
        @options=Option.generic_options().search(filter).result()
      end
      render json: {error: nil, data: @options}
    rescue ActiveRecord::RecordNotFound => e
      render json:{error: "per il museo corrente non esiste nessuna scheda con la chiave richiesta", data: nil}
    rescue ActionController::ParameterMissing => e
      render json:{error: {missing_parameter: e.to_s}, data: nil}
    rescue RuntimeError => e
      render json:{error: e, data: nil}
    end
  end

  def create
    begin
      option_data=params.require(:option).permit(:name, :key, :value)
      @option=Option.new(option_data)
      @option.museum_id=@museum.id if @museum
      if @option.save
        render json: {error: nil, data: @option}
      else
        render json: {error: @option.errors.full_messages, data: @option}
      end
    rescue ActiveRecord::RecordNotFound => e
      render json:{error: "per il museo corrente non esiste nessuna scheda con la chiave richiesta", data: nil}
    rescue ActionController::ParameterMissing => e
      render json:{error: {missing_parameter: e.to_s}, data: nil}
    rescue RuntimeError => e
      render json:{error: e.messare, data: nil}
    end
  end

  def update
    begin
      option_id=params.require(:id)
      option_data=params.require(:option).permit(:name, :key, :value)
      @option=Option.museum_options(@museum.id).find(option_id)

      if @option.update_attributes(option_data)
        render json: {error: nil, data: @option}
      else
        render json: {error: @option.errors.full_messages, data: @option}
      end
    rescue ActiveRecord::RecordNotFound => e
      render json:{error: "per il museo corrente non esiste nessuna scheda con la chiave richiesta", data: nil}
    rescue ActionController::ParameterMissing => e
      render json:{error: {missing_parameter: e.to_s}, data: nil}
    rescue RuntimeError => e
      render json:{error: e.message, data: nil}
    end
  end
  def destroy
    begin
      option_id=params.require(:id)
      raise "utente non abilitato" unless @user.is_admin?

      @option=Option.museum_options(@museum.id).find(option_id)
      raise "identificativo scheda non corretto o museo non abilitato" if @option.blank?

      if @option.destroy
        render json: {error: nil, data: "option #{option_id} cancellata correttamente"}
      else
        render json: {error: @option.errors.full_messages, data: @option}
      end


    rescue ActionController::ParameterMissing => e
      render json:{error: {missing_parameter: e.to_s}, data: nil}
    rescue RuntimeError => e
      render json:{error: e.message, data: nil}
    end
  end


end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.haml
= form_for @option do |f|
  - if @option.errors.any?
    #error_explanation
      %h2= "#{pluralize(@option.errors.count, "error")} prohibited this option from being saved:"
      %ul
        - @option.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :museum_id
    = f.number_field :museum_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :key
    = f.text_field :key
  .field
    = f.label :value
    = f.text_field :value
  .actions
    = f.submit 'Save'

app/views/options/edit.html.haml
%h1 Editing option

= render 'form'

= link_to 'Show', @option
\|
= link_to 'Back', options_path

app/views/options/index.html.haml
%h1 Listing options

%table
  %tr
    %th Museum
    %th Name
    %th Key
    %th Value
    %th
    %th
    %th

  - @options.each do |option|
    %tr
      %td= option.museum_id
      %td= option.name
      %td= option.key
      %td= option.value
      %td= link_to 'Show', option
      %td= link_to 'Edit', edit_option_path(option)
      %td= link_to 'Destroy', option, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Option', new_option_path

app/views/options/new.html.haml
%h1 New option

= render 'form'

= link_to 'Back', options_path

app/views/options/show.html.haml
%p#notice= notice

%p
  %b Museum:
  = @option.museum_id
%p
  %b Name:
  = @option.name
%p
  %b Key:
  = @option.key
%p
  %b Value:
  = @option.value

= link_to 'Edit', edit_option_path(@option)
\|
= link_to 'Back', options_path